travis:
  secure:
    BINSTAR_TOKEN: FOAFyu2B6Xpx5W8vV0IRZ2CPhwpb53rn5X6s4e4ZzdqE/Nx9HZUFQsuNbdeTUWfhNlL1mRqmBp/iXDJY1SUBgfvMCMkpMddNJV+8/x6cUmUVAM9MFWThAX/JZjyUTa5G8G2SEWDd+OKU/oY6vsRyHBlUFpFqOCJNrgvsDlmbSL8nk1Wfdsp8NbTy33giM5UTLJyoAOUgttie5YlAHYGnf4WfYbf0aNDvdz7ac3kWaY1AQoljGOSlxm7OFyPo1KToLG3aCK4GD/exRZE1gm+cuHzUZui8WTAAe1yw2UyLcu5hFGK3KI4lhIgrYp+Q4e41KDzJlVI5Ydk0sfaZ5xV+i1YvC925iIv0cP60pzw+EQrcBjnJfMVx/dh69vVAUWTv+OIa1UkdEDlTVyKdm1rg9qTH2v9cDcgwbx1/VTSsPzecmilSphLzL6tPOHkHah1+YqKdRgORIXyl/ayQcnCZFe5kjBZ9xu9pIy2A0xVGiR/r/ZKPl071LstfP6ELPYSJSB3vdzfTBgCJ+phNtIk+Btq68OgviyTotT1wACczMfOvzII4e0Chp/QKGnv2Q+nGhR48Nzg4kvmy/SeBI3OsAn0Wpxct0iThgsDjYsoRxEyleTPtkXY+kcXeCMbmopvyEB9VHNc4qzvIGXdRgDtnb6+FHJ15LMIfH8t7e39f8C4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
